/*
Program Name: EECS 348 Assignment 3
Author: Lillian Bailey
Brief Description: Program prioritizes emails from a company CEO using a max heap. Emails are prioritized first by sender then by date.
If two emails have the same sender priority, the newer email is read first.
Inputs: File of commands (EMAIL, NEXT, READ, COUNT)
Outputs: NEXT displays the highest-priority email, COUNT displays the number of unread emails.
Collaborators: Original code generated by Gemini AI as per assignment 2 directiv, but modified by Lillian Bailey also as per directive.
Creation Date: 01OCT2026
Code Source Note: The original version of this code was generated by Gemini AI. I marked this here so I could avoid a bunch of "This code was made by X" comments
*/

//TO RUN THIS PROGRAM CORRECTLY, RUN THE PROGRAM AS ./EECS348Assignment2LBExecutable < filename.txt
//THE PROGRAM TAKES THE FILENAME FROM THE COMMAND TO RUN IT, NOT FROM A TEXT PROMPT IN THE PROGRAM RUNTIME
#include <iostream>
#include <string>
#include <sstream>

// Custom object to represent individual Emails
class Email {
private:
    std::string sender;
    std::string subject;
    std::string date; // Format: MM-DD-YYYY

    // Convert sender category string to integer priority rank (higher = higher priority)
    int getSenderPriority() const {
        if (sender == "Boss") return 5;
        if (sender == "Subordinate") return 4;
        if (sender == "Peer") return 3;
        if (sender == "ImportantPerson") return 2;
        if (sender == "OtherPerson") return 1;
        return 0;
    }

    // Convert MM-DD-YYYY into YYYYMMDD string for simple lexicographical comparison
    std::string getFormattedDate() const {
        if (date.length() != 10) return date;
        std::string mm = date.substr(0, 2);
        std::string dd = date.substr(3, 2);
        std::string yyyy = date.substr(6, 4);
        return yyyy + mm + dd;
    }

public:
    Email() : sender(""), subject(""), date("") {}

    Email(const std::string& s, const std::string& sub, const std::string& d)
        : sender(s), subject(sub), date(d) {}

    std::string getSender() const { return sender; }
    std::string getSubject() const { return subject; }
    std::string getDate() const { return date; }

    // Comparator overload for MaxHeap priority ordering:
    // 1. Primary: Sender Priority Rank (Higher wins)
    // 2. Secondary: Date (Newer wins)
    bool operator<(const Email& other) const {
        int p1 = this->getSenderPriority();
        int p2 = other.getSenderPriority();

        if (p1 != p2) {
            return p1 < p2;
        }
        return this->getFormattedDate() < other.getFormattedDate();
    }

    bool operator>(const Email& other) const {
        return other < *this;
    }
};

// Node structure for list-based heap
struct Node {
    Email data;
    Node* next;
    Node(const Email& email) : data(email), next(nullptr) {}
};

// Linked-list implementation of a MaxHeap
class MaxHeap {
private:
    Node* head;
    int heapSize;

    // Helper to get element at index (0-indexed)
    Node* getNodeAt(int index) {
        Node* curr = head;
        for (int i = 0; i < index && curr != nullptr; ++i) {
            curr = curr->next;
        }
        return curr;
    }

    void swapNodes(Node* a, Node* b) {
        Email temp = a->data;
        a->data = b->data;
        b->data = temp;
    }

    void heapifyUp(int index) {
        while (index > 0) {
            int parentIndex = (index - 1) / 2;
            Node* currNode = getNodeAt(index);
            Node* parentNode = getNodeAt(parentIndex);

            // If current is greater than parent, swap up
            if (currNode->data > parentNode->data) {
                swapNodes(currNode, parentNode);
                index = parentIndex;
            } else {
                break;
            }
        }
    }

    void heapifyDown(int index) {
        while (true) {
            int leftChild = 2 * index + 1;
            int rightChild = 2 * index + 2;
            int largest = index;

            Node* largestNode = getNodeAt(largest);

            if (leftChild < heapSize) {
                Node* leftNode = getNodeAt(leftChild);
                if (leftNode->data > largestNode->data) {
                    largest = leftChild;
                    largestNode = leftNode;
                }
            }

            if (rightChild < heapSize) {
                Node* rightNode = getNodeAt(rightChild);
                if (rightNode->data > largestNode->data) {
                    largest = rightChild;
                    largestNode = rightNode;
                }
            }

            if (largest != index) {
                Node* currNode = getNodeAt(index);
                swapNodes(currNode, largestNode);
                index = largest;
            } else {
                break;
            }
        }
    }

public:
    MaxHeap() : head(nullptr), heapSize(0) {}

    ~MaxHeap() {
        while (head != nullptr) {
            Node* temp = head;
            head = head->next;
            delete temp;
        }
    }

    int getSize() const {
        return heapSize;
    }

    bool isEmpty() const {
        return heapSize == 0;
    }

    void insert(const Email& email) {
        Node* newNode = new Node(email);
        if (head == nullptr) {
            head = newNode;
        } else {
            Node* last = getNodeAt(heapSize - 1);
            last->next = newNode;
        }
        heapSize++;
        heapifyUp(heapSize - 1);
    }

    Email peek() const {
        if (isEmpty()) {
            return Email();
        }
        return head->data;
    }

    void pop() {
        if (isEmpty()) return;

        if (heapSize == 1) {
            delete head;
            head = nullptr;
            heapSize = 0;
            return;
        }

        Node* lastNodePrev = getNodeAt(heapSize - 2);
        Node* lastNode = lastNodePrev->next;

        // Move last node's data to root
        head->data = lastNode->data;

        // Detach and delete last node
        lastNodePrev->next = nullptr;
        delete lastNode;
        heapSize--;

        heapifyDown(0);
    }
};

// Object representing the CEO's Inbox Handler
class CEOInboxManager {
private:
    MaxHeap inboxHeap;

public:
    void processCommand(const std::string& line) {
        if (line.empty()) return;

        if (line.rfind("EMAIL", 0) == 0) {
            // Remove "EMAIL " prefix
            std::string data = line.substr(6);
            std::stringstream ss(data);

            std::string sender, subject, date;
            std::getline(ss, sender, ',');
            std::getline(ss, subject, ',');
            std::getline(ss, date, ',');

            // Trim leading spaces if present
            if (!sender.empty() && sender[0] == ' ') sender = sender.substr(1);
            if (!subject.empty() && subject[0] == ' ') subject = subject.substr(1);
            if (!date.empty() && date[0] == ' ') date = date.substr(1);

            inboxHeap.insert(Email(sender, subject, date));
        } 
        else if (line == "COUNT") {
            std::cout << "There are " << inboxHeap.getSize() << " emails to read.\n";
        } 
        else if (line == "NEXT") {
            if (!inboxHeap.isEmpty()) {
                Email top = inboxHeap.peek();
                std::cout << "Next email:\n";
                std::cout << "Sender: " << top.getSender() << "\n";
                std::cout << "Subject: " << top.getSubject() << "\n";
                std::cout << "Date: " << top.getDate() << "\n";
            }
        } 
        else if (line == "READ") {
            if (!inboxHeap.isEmpty()) {
                inboxHeap.pop();
            }
        }
    }
};

int main() {
    CEOInboxManager manager;
    std::string line;

    while (std::getline(std::cin, line)) {
        manager.processCommand(line);
    }

    return 0;
}